name: done
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.0-271.4.beta <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.20.0

  flutter_slidable: 0.6.0

  cupertino_icons: ^1.0.2

  logging: ^1.0.2

  hive: ^2.2.3

  bloc: ^8.0.3

  flutter_bloc: ^8.0.1

  provider: ^6.0.3

  firebase_analytics: ^9.3.0

  flutter_localizations:
    sdk: flutter
  
  intl: ^0.17.0

  easy_localization: ^3.0.1

  equatable: ^2.0.3

  uuid: ^3.0.6

  meta: ^1.8.0

  internet_connection_checker: ^0.0.1+4

  http: ^0.13.5

  rxdart: ^0.27.5
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  hive_generator: ^1.1.3
  build_runner: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0




flutter:
  generate: true
  uses-material-design: true


  assets:
    - assets/lang/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

