// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6xTF5bdAgvX0GqckP8GvijOn-CreJ5RE',
    appId: '1:246132011158:web:ea793d6d05b52ab4fd12b7',
    messagingSenderId: '246132011158',
    projectId: 'done-66af5',
    authDomain: 'done-66af5.firebaseapp.com',
    storageBucket: 'done-66af5.appspot.com',
    measurementId: 'G-MMFJWJTSCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfnSKGXCI5K1-hqO5uRrI4MdXr2cByxx8',
    appId: '1:246132011158:android:5e2643e07cfdb739fd12b7',
    messagingSenderId: '246132011158',
    projectId: 'done-66af5',
    storageBucket: 'done-66af5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-WAr1aPftWgTFJEyDAj1jxH5aZtTn0xA',
    appId: '1:246132011158:ios:8b0018f454ea23b2fd12b7',
    messagingSenderId: '246132011158',
    projectId: 'done-66af5',
    storageBucket: 'done-66af5.appspot.com',
    iosClientId: '246132011158-6ggfmnt091b5cnf5b78qtjk7s3nm9og7.apps.googleusercontent.com',
    iosBundleId: 'com.example.done',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-WAr1aPftWgTFJEyDAj1jxH5aZtTn0xA',
    appId: '1:246132011158:ios:8b0018f454ea23b2fd12b7',
    messagingSenderId: '246132011158',
    projectId: 'done-66af5',
    storageBucket: 'done-66af5.appspot.com',
    iosClientId: '246132011158-6ggfmnt091b5cnf5b78qtjk7s3nm9og7.apps.googleusercontent.com',
    iosBundleId: 'com.example.done',
  );
}
